plugins {
    id 'java'
    id 'maven-publish'
    id 'org.springframework.boot' version '3.3.4' // latest Boot
    id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.pinakis.spring'
version = '1.0.0'
description = 'Spring-Boot-REST'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    // Lombok removed – no longer needed with records
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}